/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "node_modules/flowbite-react/dist/**/*.js",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#241a00",
        "on-surface-variant": "#494551",
        "surface-container-high": "#ece6ee",
        "on-tertiary": "#ffffff",
        "inverse-surface": "#322f35",
        "on-secondary-fixed": "#1f1635",
        "surface-container-low": "#f8f2fa",
        "on-tertiary-fixed-variant": "#594400",
        "on-primary": "#ffffff",
        "on-error": "#ffffff",
        "surface-container": "#f2ecf4",
        secondary: "#63597c",
        "inverse-primary": "#cfbcff",
        "inverse-on-surface": "#f5eff7",
        "on-background": "#1d1b20",
        "tertiary-container": "#c9a74d",
        "surface-variant": "#e6e0e9",
        error: "#ba1a1a",
        "on-secondary-fixed-variant": "#4b4263",
        "on-tertiary-container": "#503d00",
        "surface-dim": "#ded8e0",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed": "#ffdf93",
        "on-secondary-container": "#645a7d",
        background: "#fdf7ff",
        "on-secondary": "#ffffff",
        surface: "#fdf7ff",
        "on-primary-container": "#e0d2ff",
        "on-error-container": "#93000a",
        "error-container": "#ffdad6",
        "surface-bright": "#fdf7ff",
        "tertiary-fixed-dim": "#e7c365",
        "secondary-container": "#e1d4fd",
        "primary-fixed": "#e9ddff",
        "surface-container-highest": "#e6e0e9",
        "primary-container": "#6750a4",
        "primary-fixed-dim": "#cfbcff",
        "on-primary-fixed": "#22005d",
        primary: "#4f378a",
        tertiary: "#765b00",
        "secondary-fixed": "#e9ddff",
        "outline-variant": "#cbc4d2",
        outline: "#7a7582",
        "surface-tint": "#6750a4",
        "on-primary-fixed-variant": "#4f378a",
        "on-surface": "#1d1b20",
        "secondary-fixed-dim": "#cdc0e9",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        stack_sm: "8px",
        sidebar_width: "280px",
        container_max_width: "1200px",
        stack_md: "16px",
        stack_lg: "32px",
        gutter: "24px",
      },
      fontFamily: {
        headline: ["Outfit", "sans-serif"],
        display: ["Outfit", "sans-serif"],
        body: ["Outfit", "sans-serif"],
        label: ["Outfit", "sans-serif"],
        sans: ["Outfit", "sans-serif"],
        "h1": ["Outfit", "sans-serif"],
        "h2": ["Outfit", "sans-serif"],
        "h3": ["Outfit", "sans-serif"],
        "body-md": ["Outfit", "sans-serif"],
        "body-lg": ["Outfit", "sans-serif"],
        "label-sm": ["Outfit", "sans-serif"],
        "label-md": ["Outfit", "sans-serif"],
      },
      fontSize: {
        "h1": ["40px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "800" }],
        "h2": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
        "h3": ["24px", { lineHeight: "1.3", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "1", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "1", letterSpacing: "0.02em", fontWeight: "600" }],
      },
    },
  },
  plugins: [
    require('flowbite/plugin')
  ],
};
